version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: docker-compose-db
    volumes:
    - db-volume:/var/lib/postgresql/data
        
  api:
    image: eng-software-ac2/prod
    environment:
      DB_HOST: database
    ports:
      - "9090:9090"

volumes:
  db-volume:
